# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtWidgets

from src.ui import utils
from src.ui.pressure_graph import PressureGraph


class DataMotorWidget(QtWidgets.QWidget):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi()

        self.valve_label_1.setText("Valve 1")
        self.valve_label_2.setText("Valve 2")
        self.valve_label_3.setText("Valve 3")
        self.valve_label_4.setText("Valve 4")
        self.valve_label_5.setText("Valve 5")

        self.valve_pushButton_1.setText("Off")
        self.valve_pushButton_2.setText("Off")
        self.valve_pushButton_3.setText("Off")
        self.valve_pushButton_4.setText("Off")
        self.valve_pushButton_5.setText("Off")

    def setupUi(self):
        self.setObjectName("Form")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(150, 75))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_1.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.pressure_graphic_view_1 = PressureGraph(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure_graphic_view_1.sizePolicy().hasHeightForWidth())
        self.pressure_graphic_view_1.setSizePolicy(sizePolicy)
        self.pressure_graphic_view_1.setMinimumSize(QtCore.QSize(400, 125))
        self.pressure_graphic_view_1.setObjectName("pressure_graphic_view_1")
        self.verticalLayout.addWidget(self.pressure_graphic_view_1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.pressure_graphic_view_2 = PressureGraph(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure_graphic_view_2.sizePolicy().hasHeightForWidth())
        self.pressure_graphic_view_2.setSizePolicy(sizePolicy)
        self.pressure_graphic_view_2.setMinimumSize(QtCore.QSize(400, 125))
        self.pressure_graphic_view_2.setObjectName("pressure_graphic_view_2")
        self.verticalLayout.addWidget(self.pressure_graphic_view_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.pressure_graphic_view_3 = PressureGraph(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure_graphic_view_3.sizePolicy().hasHeightForWidth())
        self.pressure_graphic_view_3.setSizePolicy(sizePolicy)
        self.pressure_graphic_view_3.setMinimumSize(QtCore.QSize(400, 125))
        self.pressure_graphic_view_3.setObjectName("pressure_graphic_view_3")
        self.verticalLayout.addWidget(self.pressure_graphic_view_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.pressure_graphic_view_4 = PressureGraph(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure_graphic_view_4.sizePolicy().hasHeightForWidth())
        self.pressure_graphic_view_4.setSizePolicy(sizePolicy)
        self.pressure_graphic_view_4.setMinimumSize(QtCore.QSize(400, 125))
        self.pressure_graphic_view_4.setObjectName("pressure_graphic_view_4")
        self.verticalLayout.addWidget(self.pressure_graphic_view_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.valve_label_1 = QtWidgets.QLabel(self)
        self.valve_label_1.setObjectName("valve_label_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.valve_label_1)
        self.valve_label_2 = QtWidgets.QLabel(self)
        self.valve_label_2.setObjectName("valve_label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.valve_label_2)
        self.valve_label_3 = QtWidgets.QLabel(self)
        self.valve_label_3.setObjectName("valve_label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.valve_label_3)
        self.valve_label_4 = QtWidgets.QLabel(self)
        self.valve_label_4.setObjectName("valve_label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.valve_label_4)
        self.valve_label_5 = QtWidgets.QLabel(self)
        self.valve_label_5.setObjectName("valve_label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.valve_label_5)
        self.valve_pushButton_1 = QtWidgets.QPushButton(self)
        self.valve_pushButton_1.setCheckable(False)
        self.valve_pushButton_1.setChecked(False)
        self.valve_pushButton_1.setObjectName("valve_pushButton_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.valve_pushButton_1)
        self.valve_pushButton_2 = QtWidgets.QPushButton(self)
        self.valve_pushButton_2.setCheckable(False)
        self.valve_pushButton_2.setChecked(False)
        self.valve_pushButton_2.setObjectName("valve_pushButton_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.valve_pushButton_2)
        self.valve_pushButton_3 = QtWidgets.QPushButton(self)
        self.valve_pushButton_3.setCheckable(False)
        self.valve_pushButton_3.setChecked(False)
        self.valve_pushButton_3.setObjectName("valve_pushButton_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.valve_pushButton_3)
        self.valve_pushButton_4 = QtWidgets.QPushButton(self)
        self.valve_pushButton_4.setCheckable(False)
        self.valve_pushButton_4.setChecked(False)
        self.valve_pushButton_4.setObjectName("valve_pushButton_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.valve_pushButton_4)
        self.valve_pushButton_5 = QtWidgets.QPushButton(self)
        self.valve_pushButton_5.setCheckable(False)
        self.valve_pushButton_5.setChecked(False)
        self.valve_pushButton_5.setObjectName("valve_pushButton_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.valve_pushButton_5)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(30, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem8)
        self.banc_label = QtWidgets.QLabel(self)
        self.banc_label.setObjectName("label")
        self.banc_label.setText("Banc de test")
        self.verticalLayout_6.addWidget(self.banc_label)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem10)
        self.banc_graphic_view = PressureGraph(self)
        self.banc_graphic_view.setMinimumSize(QtCore.QSize(500, 150))
        self.banc_graphic_view.setObjectName("banc_graphic_view")
        self.verticalLayout_6.addWidget(self.banc_graphic_view)
        spacerItem11 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem11)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        #self.retranslateUi(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_5.setText(_translate("Form", "Valve 1"))
        self.pushButton_4.setText(_translate("Form", "Valve  2"))
        self.pushButton_3.setText(_translate("Form", "Valve  3"))
        self.pushButton_2.setText(_translate("Form", "Valve  4"))
        self.pushButton.setText(_translate("Form", "Valve  5"))
        self.pushButton_6.setText(_translate("Form", "Indicator button"))
        self.pushButton_7.setText(_translate("Form", "Indicator button"))
        self.pushButton_8.setText(_translate("Form", "Indicator button"))
        self.pushButton_9.setText(_translate("Form", "Indicator button"))
        self.pushButton_10.setText(_translate("Form", "Indicator button"))
        self.label.setText(_translate("Form", "Banc de test"))
        self.pushButton_11.setText(_translate("Form", "PushButton"))

    def set_valve_pushButton_off(self, button: QtWidgets.QPushButton):
        button.setText("Off")
        button.setStyleSheet('background-color: #ec0000')

    def set_valve_pushButton_on(self, button: QtWidgets.QPushButton):
        button.setText("On")
        button.setStyleSheet('background-color: #00ff1a')

    def draw_pressure_graph_1(self, timestamps: list, pressures: list):
        self.pressure_graphic_view_1.draw_altitude_curve(timestamps, pressures)

    def draw_pressure_graph_2(self, timestamps: list, pressures: list):
        self.pressure_graphic_view_2.draw_altitude_curve(timestamps, pressures)

    def draw_pressure_graph_3(self, timestamps: list, pressures: list):
        self.pressure_graphic_view_3.draw_altitude_curve(timestamps, pressures)

    def draw_pressure_graph_4(self, timestamps: list, pressures: list):
        self.pressure_graphic_view_4.draw_altitude_curve(timestamps, pressures)

    def draw_pressure_graph_banc(self, timestamps: list, pressures: list):
        self.banc_graphic_view.draw_altitude_curve(timestamps, pressures)

    def reset(self):
        self.pressure_graphic_view_1.reset()
        self.pressure_graphic_view_2.reset()
        self.pressure_graphic_view_3.reset()
        self.pressure_graphic_view_4.reset()
        self.banc_graphic_view.reset()
