# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 590)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.postAnalysisWidget = QtWidgets.QTabWidget(Dialog)
        self.postAnalysisWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.postAnalysisWidget.setObjectName("postAnalysisWidget")
        self.height = QtWidgets.QWidget()
        self.height.setObjectName("height")
        self.gridLayout = QtWidgets.QGridLayout(self.height)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.postSpeedAccLayout = QtWidgets.QHBoxLayout()
        self.postSpeedAccLayout.setObjectName("postSpeedAccLayout")
        self.accLayout = QtWidgets.QVBoxLayout()
        self.accLayout.setObjectName("accLayout")
        self.accLabLayout = QtWidgets.QHBoxLayout()
        self.accLabLayout.setObjectName("accLabLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.accLabLayout.addItem(spacerItem)
        self.accLabel = QtWidgets.QLabel(self.height)
        self.accLabel.setObjectName("accLabel")
        self.accLabLayout.addWidget(self.accLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.accLabLayout.addItem(spacerItem1)
        self.accLayout.addLayout(self.accLabLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.accLayout.addItem(spacerItem2)
        self.postSpeedAccLayout.addLayout(self.accLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.postSpeedAccLayout.addItem(spacerItem3)
        self.speedLayout = QtWidgets.QVBoxLayout()
        self.speedLayout.setObjectName("speedLayout")
        self.speedLabLayout = QtWidgets.QHBoxLayout()
        self.speedLabLayout.setObjectName("speedLabLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.speedLabLayout.addItem(spacerItem4)
        self.speedLabel = QtWidgets.QLabel(self.height)
        self.speedLabel.setObjectName("speedLabel")
        self.speedLabLayout.addWidget(self.speedLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.speedLabLayout.addItem(spacerItem5)
        self.speedLayout.addLayout(self.speedLabLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.speedLayout.addItem(spacerItem6)
        self.postSpeedAccLayout.addLayout(self.speedLayout)
        self.gridLayout.addLayout(self.postSpeedAccLayout, 1, 0, 1, 1)
        self.postHeightLayout = QtWidgets.QHBoxLayout()
        self.postHeightLayout.setObjectName("postHeightLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.postHeightLayout.addItem(spacerItem7)
        self.subHeightLayout = QtWidgets.QVBoxLayout()
        self.subHeightLayout.setObjectName("subHeightLayout")
        self.postHeightTitleLayout = QtWidgets.QHBoxLayout()
        self.postHeightTitleLayout.setObjectName("postHeightTitleLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.postHeightTitleLayout.addItem(spacerItem8)
        self.postHeightLabel = QtWidgets.QLabel(self.height)
        self.postHeightLabel.setObjectName("postHeightLabel")
        self.postHeightTitleLayout.addWidget(self.postHeightLabel)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.postHeightTitleLayout.addItem(spacerItem9)
        self.subHeightLayout.addLayout(self.postHeightTitleLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.subHeightLayout.addItem(spacerItem10)
        self.postHeightLayout.addLayout(self.subHeightLayout)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.postHeightLayout.addItem(spacerItem11)
        self.gridLayout.addLayout(self.postHeightLayout, 0, 0, 1, 1)
        self.postAnalysisWidget.addTab(self.height, "")
        self.temperatureNangle = QtWidgets.QWidget()
        self.temperatureNangle.setObjectName("temperatureNangle")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.temperatureNangle)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainTempNAngleLayout = QtWidgets.QHBoxLayout()
        self.mainTempNAngleLayout.setObjectName("mainTempNAngleLayout")
        self.postTemperatureLayout = QtWidgets.QVBoxLayout()
        self.postTemperatureLayout.setObjectName("postTemperatureLayout")
        self.postTempTitleLayout = QtWidgets.QHBoxLayout()
        self.postTempTitleLayout.setObjectName("postTempTitleLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.postTempTitleLayout.addItem(spacerItem12)
        self.postTempLabel = QtWidgets.QLabel(self.temperatureNangle)
        self.postTempLabel.setObjectName("postTempLabel")
        self.postTempTitleLayout.addWidget(self.postTempLabel)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.postTempTitleLayout.addItem(spacerItem13)
        self.postTemperatureLayout.addLayout(self.postTempTitleLayout)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.postTemperatureLayout.addItem(spacerItem14)
        self.postTempGraphLayout = QtWidgets.QVBoxLayout()
        self.postTempGraphLayout.setObjectName("postTempGraphLayout")
        self.postTemperatureLayout.addLayout(self.postTempGraphLayout)
        self.mainTempNAngleLayout.addLayout(self.postTemperatureLayout)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mainTempNAngleLayout.addItem(spacerItem15)
        self.angleLayout = QtWidgets.QVBoxLayout()
        self.angleLayout.setObjectName("angleLayout")
        self.angleLabLayout = QtWidgets.QHBoxLayout()
        self.angleLabLayout.setObjectName("angleLabLayout")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.angleLabLayout.addItem(spacerItem16)
        self.anglerLabel = QtWidgets.QLabel(self.temperatureNangle)
        self.anglerLabel.setObjectName("anglerLabel")
        self.angleLabLayout.addWidget(self.anglerLabel)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.angleLabLayout.addItem(spacerItem17)
        self.angleLayout.addLayout(self.angleLabLayout)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.angleLayout.addItem(spacerItem18)
        self.subAngleLayout = QtWidgets.QHBoxLayout()
        self.subAngleLayout.setObjectName("subAngleLayout")
        self.angleLayout.addLayout(self.subAngleLayout)
        self.mainTempNAngleLayout.addLayout(self.angleLayout)
        self.gridLayout_2.addLayout(self.mainTempNAngleLayout, 0, 0, 1, 1)
        self.postAnalysisWidget.addTab(self.temperatureNangle, "")
        self.stress = QtWidgets.QWidget()
        self.stress.setObjectName("stress")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.stress)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stressLaout = QtWidgets.QVBoxLayout()
        self.stressLaout.setObjectName("stressLaout")
        self.stressLabLayout = QtWidgets.QHBoxLayout()
        self.stressLabLayout.setObjectName("stressLabLayout")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stressLabLayout.addItem(spacerItem19)
        self.stressLabel = QtWidgets.QLabel(self.stress)
        self.stressLabel.setObjectName("stressLabel")
        self.stressLabLayout.addWidget(self.stressLabel)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stressLabLayout.addItem(spacerItem20)
        self.stressLaout.addLayout(self.stressLabLayout)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.stressLaout.addItem(spacerItem21)
        self.subStressLayout = QtWidgets.QVBoxLayout()
        self.subStressLayout.setObjectName("subStressLayout")
        self.stressLaout.addLayout(self.subStressLayout)
        self.gridLayout_4.addLayout(self.stressLaout, 0, 0, 1, 1)
        self.postAnalysisWidget.addTab(self.stress, "")
        self.gridLayout_3.addWidget(self.postAnalysisWidget, 0, 0, 1, 1)
        self.menuLayout = QtWidgets.QHBoxLayout()
        self.menuLayout.setObjectName("menuLayout")
        self.returnPush = QtWidgets.QPushButton(Dialog)
        self.returnPush.setObjectName("returnPush")
        self.menuLayout.addWidget(self.returnPush)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.menuLayout.addItem(spacerItem22)
        self.closePush = QtWidgets.QPushButton(Dialog)
        self.closePush.setObjectName("closePush")
        self.menuLayout.addWidget(self.closePush)
        self.gridLayout_3.addLayout(self.menuLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.postAnalysisWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.accLabel.setText(_translate("Dialog", "Accélération"))
        self.speedLabel.setText(_translate("Dialog", "Vitesse"))
        self.postHeightLabel.setText(_translate("Dialog", "Altitude"))
        self.postAnalysisWidget.setTabText(self.postAnalysisWidget.indexOf(self.height), _translate("Dialog", "Altitude"))
        self.postTempLabel.setText(_translate("Dialog", "Température dans la fusée"))
        self.anglerLabel.setText(_translate("Dialog", "Angle de la fusée"))
        self.postAnalysisWidget.setTabText(self.postAnalysisWidget.indexOf(self.temperatureNangle), _translate("Dialog", "Température et angle"))
        self.stressLabel.setText(_translate("Dialog", "Pression"))
        self.postAnalysisWidget.setTabText(self.postAnalysisWidget.indexOf(self.stress), _translate("Dialog", "Pression"))
        self.returnPush.setText(_translate("Dialog", "Retour"))
        self.closePush.setText(_translate("Dialog", "Fermer"))

