# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(837, 580)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.postAnalysisWidget = QtGui.QTabWidget(Dialog)
        self.postAnalysisWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.postAnalysisWidget.setObjectName(_fromUtf8("postAnalysisWidget"))
        self.height = QtGui.QWidget()
        self.height.setObjectName(_fromUtf8("height"))
        self.gridLayout = QtGui.QGridLayout(self.height)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.postSpeedAccLayout = QtGui.QHBoxLayout()
        self.postSpeedAccLayout.setObjectName(_fromUtf8("postSpeedAccLayout"))
        self.accLayout = QtGui.QVBoxLayout()
        self.accLayout.setObjectName(_fromUtf8("accLayout"))
        self.accLabLayout = QtGui.QHBoxLayout()
        self.accLabLayout.setObjectName(_fromUtf8("accLabLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.accLabLayout.addItem(spacerItem)
        self.accLabel = QtGui.QLabel(self.height)
        self.accLabel.setObjectName(_fromUtf8("accLabel"))
        self.accLabLayout.addWidget(self.accLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.accLabLayout.addItem(spacerItem1)
        self.accLayout.addLayout(self.accLabLayout)
        self.accGraph = QtGui.QGraphicsView(self.height)
        self.accGraph.setObjectName(_fromUtf8("accGraph"))
        self.accLayout.addWidget(self.accGraph)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.accLayout.addItem(spacerItem2)
        self.postSpeedAccLayout.addLayout(self.accLayout)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.postSpeedAccLayout.addItem(spacerItem3)
        self.speedLayout = QtGui.QVBoxLayout()
        self.speedLayout.setObjectName(_fromUtf8("speedLayout"))
        self.speedLabLayout = QtGui.QHBoxLayout()
        self.speedLabLayout.setObjectName(_fromUtf8("speedLabLayout"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.speedLabLayout.addItem(spacerItem4)
        self.speedLabel = QtGui.QLabel(self.height)
        self.speedLabel.setObjectName(_fromUtf8("speedLabel"))
        self.speedLabLayout.addWidget(self.speedLabel)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.speedLabLayout.addItem(spacerItem5)
        self.speedLayout.addLayout(self.speedLabLayout)
        self.speedGraph = QtGui.QGraphicsView(self.height)
        self.speedGraph.setObjectName(_fromUtf8("speedGraph"))
        self.speedLayout.addWidget(self.speedGraph)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.speedLayout.addItem(spacerItem6)
        self.postSpeedAccLayout.addLayout(self.speedLayout)
        self.gridLayout.addLayout(self.postSpeedAccLayout, 1, 0, 1, 1)
        self.postHeightLayout = QtGui.QHBoxLayout()
        self.postHeightLayout.setObjectName(_fromUtf8("postHeightLayout"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.postHeightLayout.addItem(spacerItem7)
        self.subHeightLayout = QtGui.QVBoxLayout()
        self.subHeightLayout.setObjectName(_fromUtf8("subHeightLayout"))
        self.postHeightTitleLayout = QtGui.QHBoxLayout()
        self.postHeightTitleLayout.setObjectName(_fromUtf8("postHeightTitleLayout"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.postHeightTitleLayout.addItem(spacerItem8)
        self.postHeightLabel = QtGui.QLabel(self.height)
        self.postHeightLabel.setObjectName(_fromUtf8("postHeightLabel"))
        self.postHeightTitleLayout.addWidget(self.postHeightLabel)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.postHeightTitleLayout.addItem(spacerItem9)
        self.subHeightLayout.addLayout(self.postHeightTitleLayout)
        self.heightGraph = QtGui.QGraphicsView(self.height)
        self.heightGraph.setObjectName(_fromUtf8("heightGraph"))
        self.subHeightLayout.addWidget(self.heightGraph)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.subHeightLayout.addItem(spacerItem10)
        self.postHeightLayout.addLayout(self.subHeightLayout)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.postHeightLayout.addItem(spacerItem11)
        self.gridLayout.addLayout(self.postHeightLayout, 0, 0, 1, 1)
        self.postAnalysisWidget.addTab(self.height, _fromUtf8(""))
        self.temperatureNangle = QtGui.QWidget()
        self.temperatureNangle.setObjectName(_fromUtf8("temperatureNangle"))
        self.gridLayout_2 = QtGui.QGridLayout(self.temperatureNangle)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mainTempNAngleLayout = QtGui.QHBoxLayout()
        self.mainTempNAngleLayout.setObjectName(_fromUtf8("mainTempNAngleLayout"))
        self.postTemperatureLayout = QtGui.QVBoxLayout()
        self.postTemperatureLayout.setObjectName(_fromUtf8("postTemperatureLayout"))
        self.postTempTitleLayout = QtGui.QHBoxLayout()
        self.postTempTitleLayout.setObjectName(_fromUtf8("postTempTitleLayout"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.postTempTitleLayout.addItem(spacerItem12)
        self.postTempLabel = QtGui.QLabel(self.temperatureNangle)
        self.postTempLabel.setObjectName(_fromUtf8("postTempLabel"))
        self.postTempTitleLayout.addWidget(self.postTempLabel)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.postTempTitleLayout.addItem(spacerItem13)
        self.postTemperatureLayout.addLayout(self.postTempTitleLayout)
        self.postTempGraphLayout = QtGui.QVBoxLayout()
        self.postTempGraphLayout.setObjectName(_fromUtf8("postTempGraphLayout"))
        self.postTempGraph = QtGui.QGraphicsView(self.temperatureNangle)
        self.postTempGraph.setObjectName(_fromUtf8("postTempGraph"))
        self.postTempGraphLayout.addWidget(self.postTempGraph)
        self.postTemperatureLayout.addLayout(self.postTempGraphLayout)
        self.mainTempNAngleLayout.addLayout(self.postTemperatureLayout)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.mainTempNAngleLayout.addItem(spacerItem14)
        self.angleLayout = QtGui.QVBoxLayout()
        self.angleLayout.setObjectName(_fromUtf8("angleLayout"))
        self.angleLabLayout = QtGui.QHBoxLayout()
        self.angleLabLayout.setObjectName(_fromUtf8("angleLabLayout"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.angleLabLayout.addItem(spacerItem15)
        self.anglerLabel = QtGui.QLabel(self.temperatureNangle)
        self.anglerLabel.setObjectName(_fromUtf8("anglerLabel"))
        self.angleLabLayout.addWidget(self.anglerLabel)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.angleLabLayout.addItem(spacerItem16)
        self.angleLayout.addLayout(self.angleLabLayout)
        self.subAngleLayout = QtGui.QHBoxLayout()
        self.subAngleLayout.setObjectName(_fromUtf8("subAngleLayout"))
        self.angleGraph = QtGui.QGraphicsView(self.temperatureNangle)
        self.angleGraph.setObjectName(_fromUtf8("angleGraph"))
        self.subAngleLayout.addWidget(self.angleGraph)
        self.angleLayout.addLayout(self.subAngleLayout)
        self.mainTempNAngleLayout.addLayout(self.angleLayout)
        self.gridLayout_2.addLayout(self.mainTempNAngleLayout, 0, 0, 1, 1)
        self.postAnalysisWidget.addTab(self.temperatureNangle, _fromUtf8(""))
        self.stress = QtGui.QWidget()
        self.stress.setObjectName(_fromUtf8("stress"))
        self.gridLayout_4 = QtGui.QGridLayout(self.stress)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.stressLaout = QtGui.QVBoxLayout()
        self.stressLaout.setObjectName(_fromUtf8("stressLaout"))
        self.stressLabLayout = QtGui.QHBoxLayout()
        self.stressLabLayout.setObjectName(_fromUtf8("stressLabLayout"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.stressLabLayout.addItem(spacerItem17)
        self.stressLabel = QtGui.QLabel(self.stress)
        self.stressLabel.setObjectName(_fromUtf8("stressLabel"))
        self.stressLabLayout.addWidget(self.stressLabel)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.stressLabLayout.addItem(spacerItem18)
        self.stressLaout.addLayout(self.stressLabLayout)
        self.subStressLayout = QtGui.QVBoxLayout()
        self.subStressLayout.setObjectName(_fromUtf8("subStressLayout"))
        self.stressGraph = QtGui.QGraphicsView(self.stress)
        self.stressGraph.setObjectName(_fromUtf8("stressGraph"))
        self.subStressLayout.addWidget(self.stressGraph)
        self.stressLaout.addLayout(self.subStressLayout)
        self.gridLayout_4.addLayout(self.stressLaout, 0, 0, 1, 1)
        self.postAnalysisWidget.addTab(self.stress, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.postAnalysisWidget, 0, 0, 1, 1)
        self.menuLayout = QtGui.QHBoxLayout()
        self.menuLayout.setObjectName(_fromUtf8("menuLayout"))
        self.returnPush = QtGui.QPushButton(Dialog)
        self.returnPush.setObjectName(_fromUtf8("returnPush"))
        self.menuLayout.addWidget(self.returnPush)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.menuLayout.addItem(spacerItem19)
        self.closePush = QtGui.QPushButton(Dialog)
        self.closePush.setObjectName(_fromUtf8("closePush"))
        self.menuLayout.addWidget(self.closePush)
        self.gridLayout_3.addLayout(self.menuLayout, 1, 0, 1, 1)
        self.postAnalysisWidget.raise_()

        self.retranslateUi(Dialog)
        self.postAnalysisWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.accLabel.setText(_translate("Dialog", "Accélération", None))
        self.speedLabel.setText(_translate("Dialog", "Vitesse", None))
        self.postHeightLabel.setText(_translate("Dialog", "Altitude", None))
        self.postAnalysisWidget.setTabText(self.postAnalysisWidget.indexOf(self.height), _translate("Dialog", "Altitude", None))
        self.postTempLabel.setText(_translate("Dialog", "Température dans la fusée", None))
        self.anglerLabel.setText(_translate("Dialog", "Angle de la fusée", None))
        self.postAnalysisWidget.setTabText(self.postAnalysisWidget.indexOf(self.temperatureNangle), _translate("Dialog", "Température et angle", None))
        self.stressLabel.setText(_translate("Dialog", "Pression", None))
        self.postAnalysisWidget.setTabText(self.postAnalysisWidget.indexOf(self.stress), _translate("Dialog", "Pression", None))
        self.returnPush.setText(_translate("Dialog", "Retour", None))
        self.closePush.setText(_translate("Dialog", "Fermer", None))

