# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight_data.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(746, 534)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.vSpeedLayout = QtGui.QVBoxLayout()
        self.vSpeedLayout.setObjectName(_fromUtf8("vSpeedLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vSpeedLayout.addItem(spacerItem)
        self.hSpeedLayout = QtGui.QHBoxLayout()
        self.hSpeedLayout.setObjectName(_fromUtf8("hSpeedLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hSpeedLayout.addItem(spacerItem1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.speedLabel = QtGui.QLabel(Dialog)
        self.speedLabel.setObjectName(_fromUtf8("speedLabel"))
        self.verticalLayout_6.addWidget(self.speedLabel)
        self.speedLCD = QtGui.QLCDNumber(Dialog)
        self.speedLCD.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    color: rgb(0, 0, 0);    \n"
"}"))
        self.speedLCD.setSmallDecimalPoint(False)
        self.speedLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.speedLCD.setObjectName(_fromUtf8("speedLCD"))
        self.verticalLayout_6.addWidget(self.speedLCD)
        self.hSpeedLayout.addLayout(self.verticalLayout_6)
        self.speedUnitLabel = QtGui.QLabel(Dialog)
        self.speedUnitLabel.setObjectName(_fromUtf8("speedUnitLabel"))
        self.hSpeedLayout.addWidget(self.speedUnitLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hSpeedLayout.addItem(spacerItem2)
        self.vSpeedLayout.addLayout(self.hSpeedLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vSpeedLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.vSpeedLayout, 0, 1, 1, 1)
        self.instantSpeedAngleLay = QtGui.QGridLayout()
        self.instantSpeedAngleLay.setObjectName(_fromUtf8("instantSpeedAngleLay"))
        self.instantHeightLay = QtGui.QHBoxLayout()
        self.instantHeightLay.setObjectName(_fromUtf8("instantHeightLay"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.instantHeightLay.addItem(spacerItem4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.heightLabel = QtGui.QLabel(Dialog)
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.verticalLayout_5.addWidget(self.heightLabel)
        self.heightLCD = QtGui.QLCDNumber(Dialog)
        self.heightLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.heightLCD.setObjectName(_fromUtf8("heightLCD"))
        self.verticalLayout_5.addWidget(self.heightLCD)
        self.instantHeightLay.addLayout(self.verticalLayout_5)
        self.heightUnitLabel = QtGui.QLabel(Dialog)
        self.heightUnitLabel.setObjectName(_fromUtf8("heightUnitLabel"))
        self.instantHeightLay.addWidget(self.heightUnitLabel)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.instantHeightLay.addItem(spacerItem5)
        self.instantSpeedAngleLay.addLayout(self.instantHeightLay, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.instantSpeedAngleLay.addItem(spacerItem6, 2, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.instantSpeedAngleLay.addItem(spacerItem7, 0, 0, 1, 1)
        self.instantAngleLay = QtGui.QHBoxLayout()
        self.instantAngleLay.setObjectName(_fromUtf8("instantAngleLay"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.instantAngleLay.addItem(spacerItem8)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.LatLCD = QtGui.QLCDNumber(Dialog)
        self.LatLCD.setNumDigits(10)
        self.LatLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.LatLCD.setObjectName(_fromUtf8("LatLCD"))
        self.verticalLayout_3.addWidget(self.LatLCD)
        self.latLabel = QtGui.QLabel(Dialog)
        self.latLabel.setObjectName(_fromUtf8("latLabel"))
        self.verticalLayout_3.addWidget(self.latLabel)
        self.instantAngleLay.addLayout(self.verticalLayout_3)
        self.angleLabel = QtGui.QLabel(Dialog)
        self.angleLabel.setText(_fromUtf8(""))
        self.angleLabel.setObjectName(_fromUtf8("angleLabel"))
        self.instantAngleLay.addWidget(self.angleLabel)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.instantAngleLay.addItem(spacerItem9)
        self.instantSpeedAngleLay.addLayout(self.instantAngleLay, 3, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.instantSpeedAngleLay.addItem(spacerItem10, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.longLCD = QtGui.QLCDNumber(Dialog)
        self.longLCD.setNumDigits(10)
        self.longLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.longLCD.setObjectName(_fromUtf8("longLCD"))
        self.verticalLayout_4.addWidget(self.longLCD)
        self.longLabel = QtGui.QLabel(Dialog)
        self.longLabel.setObjectName(_fromUtf8("longLabel"))
        self.verticalLayout_4.addWidget(self.longLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.instantSpeedAngleLay.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.gridLayout.addLayout(self.instantSpeedAngleLay, 1, 1, 1, 1)
        self.AnalysisLayout = QtGui.QHBoxLayout()
        self.AnalysisLayout.setObjectName(_fromUtf8("AnalysisLayout"))
        self.startButton = QtGui.QPushButton(Dialog)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.AnalysisLayout.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(Dialog)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.AnalysisLayout.addWidget(self.stopButton)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.AnalysisLayout.addItem(spacerItem13)
        self.analyseButton = QtGui.QPushButton(Dialog)
        self.analyseButton.setObjectName(_fromUtf8("analyseButton"))
        self.AnalysisLayout.addWidget(self.analyseButton)
        self.exitPush = QtGui.QPushButton(Dialog)
        self.exitPush.setObjectName(_fromUtf8("exitPush"))
        self.AnalysisLayout.addWidget(self.exitPush)
        self.gridLayout.addLayout(self.AnalysisLayout, 2, 0, 1, 3)
        self.mapLayout = QtGui.QVBoxLayout()
        self.mapLayout.setObjectName(_fromUtf8("mapLayout"))
        self.mapGraphLab = QtGui.QLabel(Dialog)
        self.mapGraphLab.setObjectName(_fromUtf8("mapGraphLab"))
        self.mapLayout.addWidget(self.mapGraphLab)
        self.gridLayout.addLayout(self.mapLayout, 0, 2, 1, 1)
        self.angleLayout = QtGui.QVBoxLayout()
        self.angleLayout.setObjectName(_fromUtf8("angleLayout"))
        self.angleGraphLab = QtGui.QLabel(Dialog)
        self.angleGraphLab.setObjectName(_fromUtf8("angleGraphLab"))
        self.angleLayout.addWidget(self.angleGraphLab)
        self.gridLayout.addLayout(self.angleLayout, 1, 2, 1, 1)
        self.heightLayout = QtGui.QVBoxLayout()
        self.heightLayout.setObjectName(_fromUtf8("heightLayout"))
        self.heightGraphLab = QtGui.QLabel(Dialog)
        self.heightGraphLab.setObjectName(_fromUtf8("heightGraphLab"))
        self.heightLayout.addWidget(self.heightGraphLab)
        self.gridLayout.addLayout(self.heightLayout, 1, 0, 1, 1)
        self.speedLayout = QtGui.QVBoxLayout()
        self.speedLayout.setObjectName(_fromUtf8("speedLayout"))
        self.speedGraphLab = QtGui.QLabel(Dialog)
        self.speedGraphLab.setObjectName(_fromUtf8("speedGraphLab"))
        self.speedLayout.addWidget(self.speedGraphLab)
        self.gridLayout.addLayout(self.speedLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.speedLabel.setText(_translate("Dialog", "Vitesse", None))
        self.speedUnitLabel.setText(_translate("Dialog", "m/s", None))
        self.heightLabel.setText(_translate("Dialog", "Altitude", None))
        self.heightUnitLabel.setText(_translate("Dialog", "m", None))
        self.latLabel.setText(_translate("Dialog", "Lattitude", None))
        self.longLabel.setText(_translate("Dialog", "Longitude", None))
        self.startButton.setText(_translate("Dialog", "Start", None))
        self.stopButton.setText(_translate("Dialog", "Arrêter la lecture", None))
        self.analyseButton.setText(_translate("Dialog", "Démarrer l\'analyse", None))
        self.exitPush.setText(_translate("Dialog", "Fermer", None))
        self.mapGraphLab.setText(_translate("Dialog", "Accelération", None))
        self.angleGraphLab.setText(_translate("Dialog", "Température", None))
        self.heightGraphLab.setText(_translate("Dialog", "Altitude", None))
        self.speedGraphLab.setText(_translate("Dialog", "Vitesse", None))

